CREATE TABLE `phones`(
    `id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `phone_number` VARCHAR(20),
    `name` VARCHAR(50),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     PRIMARY KEY (`id`)
);